spring:
  datasource:
    url: jdbc:mysql://localhost:3306/publicity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      d#dl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  servlet:
    multipart:
      max-request-size: 128MB
      max-file-size: 128MB
     # max_allowed_packet: 128MB

#email
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: daria.cringasu@student.upt.ro
#    password: Lk09A@31
#    smtp:
#      auth: true
#      starttls:
#        enable: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dariacringasu05@gmail.com
    password: hxldutguvafpjypq

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true